### ISSUE TITLE
Revise activity bar to display more useful information

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#102]
Changing display bar from MB/GB to number of images. Will indicate number of images incoming from dashcam, total on phone, and total uploaded for the day.

**Comment by joshkauffman** [comment]
Would it be a lot to have it toggle-able between ImageQty and DataSize? 

Reason being that if I had just a small amount of data remaining to upload, I may be ok with running it over cellular connection. Whereas if all I know is the amount of images, I don't have an intuitive sense for how much that could eat up my data allocation.

But overall think this is a more useful metric.

**Comment by jayalberts** [comment]
We have final designs for this and work started today - we might be able to work it into the `Week 2307` release instead of `Week 2308`

**Comment by jayalberts** [comment]
Initial drive tests done. This is an improvement but still some refining to do.

**Comment by jayalberts** [comment]
Really happy with the progress here. On track for delivery next week.

**Comment by jayalberts** [comment]
Released with 5.1.6
