### ISSUE TITLE
Buzz reports

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#105]
One of Hivemapper’s key strengths is the freshness of our map. With many cameras on the road mapping frequently, our swarm of Hivemappers are bound to capture dynamic events on camera that would otherwise be impossible for our competitors to identify or visualize. Hivemapper can do this with high-fidelity and high-frequency. 

Buzz will be a feature which is iterated on many times. In version 1, we want to give the ability for contributors to "buzz" in a report of something noteworthy, and we will learn what type of dynamic events are being captured.

**Comment by jayalberts** [comment]
Pushed this out 1 week

**Comment by jayalberts** [comment]
Pending some backend work, waiting for handoff.

**Comment by jayalberts** [comment]
Backend work is WIP

**Comment by jayalberts** [comment]
Handing off for mobile dev

**Comment by jayalberts** [comment]
Mobile dev in review, need to test next week

**Comment by EvaMaria02** [comment]
when the contributors press the Buzz a set of images will be taken, if the contribuitor is on celular and already has 3000 images to be uploaded those Buzz images will be uploaded with priority ?

**Comment by jayalberts** [comment]
> when the contributors press the Buzz a set of images will be taken, if the contribuitor is on celular and already has 3000 images to be uploaded those Buzz images will be uploaded with priority ?

Not in v1, but in subsequent versions we will want to. First priority is to learn how people are using the buzz reporting tool.

**Comment by jayalberts** [comment]
v1 released in 5.5.2
