### ISSUE TITLE
Improved in-app notification system

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#107]

**Comment by joshkauffman** [comment]
Since there have been a few users reporting in Discord about not realizing they could swipe away the notification banner, consider adding a small X to close it out too.

**Comment by jayalberts** [comment]
Moved this up a week. This will be an iterative process, but expecting to squeeze in some updates as soon as `Week 2307` or `Week 2308`

**Comment by jayalberts** [comment]
Closing this task and opening new ones to get more specific about the fixes we are going to make.
