### ISSUE TITLE
Show contributor when HONEY rewards are pending

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#11]
Contributors are currently confused about the minting schedule related to their contributions. The misconception is that HONEY is minted immediately after a contribution is made. In reality, a complex calculation is run each week to determine global progress which impacts the overall amount of HONEY minted and distributed.

We are introducing a "pending" rewards state so a contributor knows that they can expect HONEY on a certain date. However, we will never be able to estimate how much HONEY due to the weekly global progress calculation.

**Comment by jayalberts** [comment]
UI is being built, next step is to handle the minting dates. On track to start internal testing next week.

**Comment by jayalberts** [comment]
nearly ready for testing

**Comment by jayalberts** [comment]
This is being internally tested

**Comment by JezusHivemapper** [comment]
Sounds like a good idea.

**Comment by jayalberts** [comment]
released in 4.99
