### ISSUE TITLE
Connect Dashcam banner at top of screen obscures upload status

### ISSUE THREAD

**Issue by MarcStevens987** [Hivemapper/Community#155]
- Bug report

**Feedback description**
I am sitting in my living room, away from my vehicle, and the app wants to connect to the HDC. I have no desire to connect to the HDC. But, the 'Connect Dashcam Wifi' banner at the top of the screen keeps appearing even if I swipe it up to make it disappear. 

The problem is that when home, the upload status is very important to watch as it decrements down. 

The 'Connect Dashcam Wifi' banner is obscuring the upload status data. 

**Additional material**
screen recording is attached.

# Bug details
### Please complete this section if you are reporting a bug

**To Reproduce**
1. Ensure you are physically away from your HDC
2. Go to 'Map' window
3. Wait a moment
4. Watch the 'Connect Dashcam Wifi' banner drop down from the top
5. Swipe it back up so that you can see the upload data, and moments later, the 'Connect Dashcam Wifi' banner reappears. 

**Expected behavior**
I would expect when data upload information not to be obscured by a constantly refreshing 'Connect Dashcam Wifi' banner. Either the banner should not refresh or the banner (or upload data) be relocated on the screen.

- Dashcam: [HDC]
- Device: [iPhone13 Pro]
- OS: [iOS 16.1.1]
- App Version [e.g. 5.1.6]
- Browser [not applicable]

https://user-images.githubusercontent.com/123485818/221685166-ccf0dd1e-a1d4-42d7-9e01-1415ffda7ca6.MP4

**Comment by jayalberts** [comment]
@MarcStevens987 this will be fixed in this week's release! I appreciate you taking the time to fill out the bug report. I will close this one as a duplicate though.
