### ISSUE TITLE
Improve Helium verification of authentic location

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#5]

**Comment by jayalberts** [comment]
This is ready to launch in next version of the app.

**Comment by jayalberts** [comment]
Released in 4.82.0

**Comment by Marianu08** [comment]
Español: Una pregunta: Los propietarios de hotsopots de la red helium verán incrementadas sus ganancias si las dathcams de hivemapper se conecta a ellos ?

English: A question: The owners of hotsopots of the helium network will see their profits increased if the hivemapper dathcams connect to them? It is a translation from Spanish to English, I apologize.
Thenks

**Comment by jayalberts** [comment]
@Marianu08 

Hivemapper está utilizando la red Helium para autenticar la ubicación de las imágenes recopiladas por los colaboradores. Teóricamente, el uso de la red Helium aumenta su valor, pero Hivemapper no puede especular sobre el retorno de la inversión (ROI) de ningún proyecto, incluido el nuestro. Esta respuesta ha sido traducida de inglés a español usando el traductor de Google.

Hivemapper is using the Helium network to authenticate location of images collected by contributors. Theoretically, usage of the Helium network increases the value of it but Hivemapper can't speculate on return on investment (ROI) of any project including our own. This answer has been translated from English to Spanish using Google translate.
