### ISSUE TITLE
Graphs not showing for Individual Contributors

### ISSUE THREAD

**Issue by Vestibule22** [Hivemapper/Community#90]
# Feedback
**What type of feedback is this?**
- Bug report

**Feedback description**
Total Tokens Earned and Total Coverage Mapped Graphs not present under every contributor.  Sincere Maroon Soil shows both graphs however, many contributors including my own Textured Grass Matches does not have them even after completing mapping/payouts.  Additionally,  

**Additional material**
If applicable: add screenshots, screen recordings, mockups or anything else to help explain your feedback. Screenshots Attached

# Bug details
### Please complete this section if you are reporting a bug

**To Reproduce**
1. Go to 'https://hivemapper.com/explorer'
2. Click on 'Contributors'
3. Scroll down to 'Textured Grass Matches'
4. See error where no graphs are present

**Expected behavior**
Expect to see graphs present on all contributors to show what they have mapped

**Please include any additional context that might be helpful**

- Browser [chrome]
[Examples 1.pdf](https://github.com/Hivemapper/Community/files/10475889/Examples.1.pdf)
[Examples 2.pdf](https://github.com/Hivemapper/Community/files/10475890/Examples.2.pdf)

**Comment by jayalberts** [comment]
@Vestibule22 - Thank you for reporting this. Currently the individual contributor graphs are updated once per week. Would you mind checking back next week to let me know if you are still experiencing this issue?

**Comment by Vestibule22** [comment]
Looks like it has now updated on my end!  Glad to see the graphs and what I have mapped so far!
