### ISSUE TITLE
App display contrast too low

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/Community#96]
@MarcStevens987
Enhancement request (new or existing features)
Mobile app

The black background of the display and light purple is too low contrast to effectively see during daytime inside of a car. Since all mapping will occur during daylight hours, can users have an option for a white background.

**Comment by jayalberts** [comment]
@MarcStevens987 - we definitely want to give more options to the user to control things like this. It hasn't been as high priority as some of the other functionality, but we will get there soon enough. Thanks for the idea!

**Comment by MarcStevens987** [comment]
Hopefully this video attaches properly but it's an example of what I'm trying to read in a bright car. Even changing the background to white would help immensely https://user-images.githubusercontent.com/123485818/219826200-af129352-154c-4fed-b4d8-1f207f2f6277.MOV

**Comment by jayalberts** [comment]
> Hopefully this video attaches properly but it's an example of what I'm trying to read in a bright car. Even changing the background to white would help immensely https://user-images.githubusercontent.com/123485818/219826200-af129352-154c-4fed-b4d8-1f207f2f6277.MOV

Unfortunately video did not load for me. I certainly understand the frustration though. We are going to take a closer look at improvements to the map tab within the next couple weeks and we will see if we can squeeze this in.

**Comment by jayalberts** [comment]
white background map on track for this month

**Comment by jayalberts** [comment]
released in 5.5.2
